az2                 = "us-west-1a"
role2               = "jenkins-server"
purpose2            = "jenkins-server"
region              = "us-west-1"
inboundport         = "8080"
inboundport2         = "22"
machine-ami         = "my-linux-ami"
bootstrap-file      = ""