az2                 = "us-west-2b"
role2               = "devapp-server"
purpose2            = "devapp-server"
region              = "us-west-2"
inboundport         = "8080"
inboundport2         = "22"
machine-ami         = "my-linux-ami"
bootstrap-file      = ""      
