az2                 = "us-east-1b"
subnet-suffix       = "b" 
role2               = "devapp-server"
purpose2            = "devapp-server"
region              = "us-east-1"
inboundport         = "8080"
machine-ami         = "my-linux-ami"
bootstrap-file      = ""      
