---
  - hosts:
      - all
    become: yes
    tasks:

      - name: Write welcome message to servers
        ansible.builtin.template:
          src: message.j2
          dest: /etc/profile.d/welcome_message.sh
          owner: root
          group: root
        # mode: '0644'

      - name: Update all packages
        yum:
          name: '*'
          state: latest
          update_cache: yes

      - name: Install docker
        yum:
          name: docker
          state: latest

      - name: Start docker
        service:
          name: docker
          state: started
          enabled: yes

  - hosts:
      - jenkins_server
    become: yes
    tasks:
      - name: install epel dependency
        ansible.builtin.template:
          src: epelrepo.j2
          dest: /etc/yum.repos.d/epelfordaemonize.repo
          owner: root
          group: root

      - name: Install needed apps git and daemonize
        yum:
          name: '{{ neededapps }}'
          state: latest


      - name: Download jenkins repo
        get_url:
          url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
          dest: /etc/yum.repos.d/jenkins.repo

      - name: Import Jenkins Key
        rpm_key:
          state: present
          key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

      - name: Install Jenkins
        yum:
          name: jenkins
          state: present

      - name: Start Jenkins
        systemd:
          name: jenkins
          state: started
          enabled: true

      - name: Sleep for 30 seconds and continue with play
        wait_for: timeout=30

      - name: Get init password Jenkins
        shell: cat /var/lib/jenkins/secrets/initialAdminPassword
        changed_when: false
        register: result

      - name: Print init password Jenkins
        debug:
          var: result.stdout