---
  - hosts:
      - all
    become: yes
    tasks:

      - name: Write welcome message to servers
        ansible.builtin.template:
          src: message.j2
          dest: /etc/profile.d/welcome_message.sh
          owner: root
          group: root

      - name: Update all packages
        yum:
          name: '*'
          state: latest
          update_cache: yes

      - name: Install docker
        yum:
          name: docker
          state: latest

      - name: Start docker
        service:
          name: docker
          state: started
          enabled: yes

  - hosts:
      - jenkins_server
    become: yes
    become_user: root
    tasks:
      - name: create jenkins user
        ansible.builtin.user:
          name: jenkins
          comment: jenkins user
          uid: 1040
          group: wheel

      - name: grant jenkins user sudoer privilege
        ansible.builtin.lineinfile:
          path: /etc/sudoers
          regexp: '%wheel ALL=(ALL) NOPASSWD: ALL'
          line: 'jenkins ALL=(ALL) NOPASSWD: ALL'

      - name: generate ssh key for jenkins
        ansible.builtin.user:
          name: jenkins
          generate_ssh_key: yes
          ssh_key_bits: 2048
          ssh_key_file: .ssh/id_rsa

      - name: Fetch the keyfile from one server to another
        fetch:
          src: "/home/jenkins/.ssh/id_rsa.pub"
          dest: "buffer/jenkinskey"
          flat: yes

      - name: install epel dependency
        ansible.builtin.template:
          src: epelrepo.j2
          dest: /etc/yum.repos.d/epelfordaemonize.repo
          owner: root
          group: root

      - name: Install needed apps git and daemonize
        yum:
          name: '{{ neededapps }}'
          state: latest

      - name: Download jenkins repo
        get_url:
          url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
          dest: /etc/yum.repos.d/jenkins.repo

      - name: Import Jenkins Key
        rpm_key:
          state: present
          key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

      - name: Install Jenkins
        yum:
          name: jenkins
          state: present

      - name: Start Jenkins
        systemd:
          name: jenkins
          state: started
          enabled: true

      - name: Sleep for 5 seconds and continue with play
        wait_for:
          timeout: 5
        delegate_to: localhost

      - name: Get init password Jenkins
        shell: cat /var/lib/jenkins/secrets/initialAdminPassword
        changed_when: false
        register: result

      - name: Print init password Jenkins
        debug:
          var: result.stdout

  - hosts:
      - dev_server
    become: yes
    become_user: root
    tasks:
      - name: copy jenkins public ssh key to dev tmp folder
        copy:
          src: "buffer/jenkinskey"
          dest: "/tmp/remote-id_rsa.pub"

      - name: copy jenkins ssh key from tmp folder to authorized key
        shell: "cat /tmp/remote-id_rsa.pub >> /home/ec2-user/.ssh/authorized_keys"
        register: addtoauth

  - hosts:
      - prod_server
    become: yes
    become_user: root
    tasks:
      - name: copy jenkins public ssh key to prod tmp folder
        copy:
          src: "buffer/jenkinskey"
          dest: "/tmp/remote-id_rsa.pub"

      - name: copy jenkins ssh key from tmp folder to authorized key
        shell: "cat /tmp/remote-id_rsa.pub >> /home/ec2-user/.ssh/authorized_keys"
        register: addtoauth