az2                 = "us-west-2a"
role2               = "ansible-server"
purpose2            = "ansible-server"
region              = "us-west-2"
inboundport         = "22"
inboundport2         = "22"
machine-ami         = "my-linux-ami"
bootstrap-file      = "ansiblenode-bootstrap"