az2                 = "us-east-1a"
role2               = "ansible-server"
purpose2            = "ansible-server"
region              = "us-east-1"
inboundport         = "22"
inboundport2         = "22"
machine-ami         = "my-linux-ami"
bootstrap-file      = "ansiblenode-bootstrap"